#!/usr/bin/env node
/**
 * Kinetic Drop token generator.
 * Input:  packages/tokens/tokens.json (source of truth)
 * Output: apps/ios/Packages/DesignSystem/Sources/DesignSystem/Generated/*.swift
 *
 * Usage: node packages/tokens/generate.mjs
 * Generated files are committed so the Xcode project builds without Node.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const tokens = JSON.parse(readFileSync(join(root, "packages/tokens/tokens.json"), "utf8"));
const outDir = join(root, "apps/ios/Packages/DesignSystem/Sources/DesignSystem/Generated");
mkdirSync(outDir, { recursive: true });

const HEADER = `// GENERATED by packages/tokens/generate.mjs from tokens.json (${tokens.meta.name} v${tokens.meta.version}).
// DO NOT EDIT — change tokens.json and re-run the generator.

import SwiftUI
`;

const hexToRGB = (hex) => {
  const h = hex.replace("#", "");
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255);
};
const swiftColor = (hex, alpha = 1) => {
  const [r, g, b] = hexToRGB(hex);
  const f = (n) => n.toFixed(4);
  return `Color(red: ${f(r)}, green: ${f(g)}, blue: ${f(b)}${alpha !== 1 ? `, opacity: ${alpha}` : ""})`;
};

// ── Colors ──────────────────────────────────────────────────────────
let colors = `${HEADER}
/// Kinetic Drop color tokens. Zero raw hex values in views — use these.
public enum InkColor {
`;
for (const [name, t] of Object.entries(tokens.color)) {
  colors += `    /// ${t.usage}\n    public static let ${name} = ${swiftColor(t.value)}\n`;
}
colors += `}\n\npublic extension InkColor {\n`;
for (const [name, t] of Object.entries(tokens.colorAlpha)) {
  colors += `    /// ${t.usage}\n    static let ${name} = ${swiftColor(t.base, t.alpha)}\n`;
}
colors += `}\n\n/// Signature gradients.\npublic enum InkGradient {\n`;
for (const [name, g] of Object.entries(tokens.gradient)) {
  colors += `    /// ${g.usage}
    public static let ${name} = LinearGradient(
        colors: [${swiftColor(g.from)}, ${swiftColor(g.to)}],
        startPoint: .topLeading, endPoint: .bottomTrailing
    )\n`;
}
colors += `}\n`;
writeFileSync(join(outDir, "Colors.swift"), colors);

// ── Spacing / Radius / Layout ───────────────────────────────────────
let metrics = `${HEADER}
/// 8pt-grid spacing tokens (pt).
public enum Spacing {
`;
for (const [name, v] of Object.entries(tokens.spacing)) {
  metrics += `    public static let ${name}: CGFloat = ${v}\n`;
}
metrics += `}

/// Corner radius tokens (pt).
public enum Radius {
`;
for (const [name, v] of Object.entries(tokens.radius)) {
  metrics += `    public static let ${name}: CGFloat = ${v}\n`;
}
metrics += `}

/// Layout constants (pt).
public enum Layout {
`;
for (const [name, v] of Object.entries(tokens.layout)) {
  metrics += `    public static let ${name}: CGFloat = ${v}\n`;
}
metrics += `}\n`;
writeFileSync(join(outDir, "Metrics.swift"), metrics);

// ── Typography ──────────────────────────────────────────────────────
let type = `${HEADER}import UIKit

/// Kinetic Drop type scale. Custom fonts (Space Grotesk / Manrope) fall back to the
/// system font until the font files are added to the app target (see apps/ios/README).
public struct TypeToken: Sendable {
    public let size: CGFloat
    public let weight: Font.Weight
    public let lineHeight: CGFloat
    public let tracking: CGFloat
    public let isUppercase: Bool
    public let isDisplay: Bool

    /// SwiftUI Font for this token (custom family with system fallback).
    public var font: Font {
        let family = isDisplay ? "Space Grotesk" : "Manrope"
        if UIFont(name: family, size: size) != nil {
            return .custom(family, size: size).weight(weight)
        }
        return .system(size: size, weight: weight)
    }
}

public enum TypeScale {
`;
const weightMap = { 400: ".regular", 500: ".medium", 600: ".semibold", 700: ".bold" };
for (const [name, t] of Object.entries(tokens.typography.scale)) {
  type += `    public static let ${name} = TypeToken(size: ${t.size}, weight: ${weightMap[t.weight]}, lineHeight: ${t.lineHeight}, tracking: ${t.tracking}, isUppercase: ${t.uppercase ? "true" : "false"}, isDisplay: ${t.font === "display" ? "true" : "false"})\n`;
}
type += `}

public extension Text {
    /// Apply a Kinetic type token (font + tracking). Uppercasing is applied at the
    /// call site with textCase(.uppercase) so localization stays intact.
    func kinetic(_ token: TypeToken) -> Text {
        font(token.font).kerning(token.tracking)
    }
}
`;
writeFileSync(join(outDir, "Typography.swift"), type);

// ── Motion ──────────────────────────────────────────────────────────
let motion = `${HEADER}
/// Motion tokens. Every animation must respect Reduce Motion at the call site.
public enum Motion {
`;
for (const [name, ms] of Object.entries(tokens.motion.duration)) {
  motion += `    public static let ${name}: TimeInterval = ${ms / 1000}\n`;
}
motion += `}

/// cubic-bezier easings from the design system, as iOS 16-compatible Animations.
/// Usage: .animation(Easing.standard(duration: Motion.standard), value: state)
public enum Easing {
`;
for (const [name, b] of Object.entries(tokens.motion.easing)) {
  motion += `    public static func ${name}(duration: TimeInterval) -> Animation {
        .timingCurve(${b[0]}, ${b[1]}, ${b[2]}, ${b[3]}, duration: duration)
    }\n`;
}
motion += `}\n`;
writeFileSync(join(outDir, "Motion.swift"), motion);

console.log("✔ Generated Swift tokens →", outDir);
