-- ============================================================================
-- Paave | Migration 0009 — AI Suggestions (Gợi ý hôm nay)
-- ============================================================================
-- Pre-computed daily AI analysis for top-20 HOSE symbols by volume.
-- Generated by GitHub Actions job at 18:45 ICT after market close.
-- Users read from this table — ZERO LLM cost per page view.
-- Spec: FRD-21 · SRD-21
-- ============================================================================

-- ---------------------------------------------------------------------------
-- ENUMS
-- ---------------------------------------------------------------------------
create type public.ai_signal_type as enum (
  'BUY_OPPORTUNITY',   -- Cơ hội mua tiềm năng
  'WATCH',             -- Đáng quan sát
  'SELL_CAUTION'       -- Cảnh báo bán
);

-- ---------------------------------------------------------------------------
-- AI SUGGESTIONS — one row per symbol per trading day
-- ---------------------------------------------------------------------------
create table public.ai_suggestions (
  id               bigserial primary key,
  symbol_code      text not null references public.symbols(code) on delete cascade,

  -- Signal
  signal_type      public.ai_signal_type not null,
  confidence_pct   int not null check (confidence_pct between 0 and 85), -- HARD CAP: never > 85
  analysis_text    text not null check (
                     char_length(analysis_text) between 1 and 150
                   ),

  -- Price context (snapshot at generation time)
  price_current    numeric(20,4),
  price_target     numeric(20,4),   -- null = no target (WATCH / SELL_CAUTION typical)
  target_pct       numeric(10,2),   -- null = no target; negative = downside target

  -- Audit trail (required for compliance review)
  skills_used      text[] not null default '{}',
  model_used       text not null,   -- 'claude-haiku-4-5' | 'claude-sonnet-4-5'
  generation_ms    int,             -- wall-clock ms for this symbol's pipeline run
  input_tokens     int,
  output_tokens    int,

  -- Lifecycle
  generated_at     timestamptz not null default now(),
  valid_until      timestamptz not null,  -- next trading day 08:30 ICT
  is_published     boolean not null default false,

  -- Prevent duplicate published rows per symbol per day
  constraint uq_ai_sugg_symbol_date unique (symbol_code, (generated_at::date))
);

-- Fast reads for Home screen (only published, still valid)
create index idx_ai_sugg_published
  on public.ai_suggestions (valid_until, confidence_pct desc)
  where is_published = true;

-- Audit / admin query by symbol
create index idx_ai_sugg_symbol
  on public.ai_suggestions (symbol_code, generated_at desc);

-- ---------------------------------------------------------------------------
-- DAILY PIPELINE RUN LOG — one row per nightly job execution
-- ---------------------------------------------------------------------------
create table public.ai_suggestion_runs (
  id              bigserial primary key,
  run_date        date not null unique,
  symbols_attempted int not null default 0,
  symbols_published int not null default 0,
  symbols_skipped   int not null default 0,  -- content-filter rejects
  total_input_tokens  int,
  total_output_tokens int,
  estimated_cost_usd  numeric(10,6),
  duration_seconds    int,
  error_message       text,   -- null = success
  started_at      timestamptz not null default now(),
  finished_at     timestamptz
);

-- ---------------------------------------------------------------------------
-- CONTENT FILTER AUDIT — log every guardrail hit
-- ---------------------------------------------------------------------------
create table public.ai_suggestion_filter_log (
  id           bigserial primary key,
  run_date     date not null,
  symbol_code  text,
  filter_type  text not null,  -- 'PROHIBITED_PHRASE' | 'CONFIDENCE_OVERFLOW' | 'UNKNOWN_SIGNAL'
  matched_text text,           -- the exact phrase or value that triggered the filter
  raw_output   text,           -- the AI's original output before correction/rejection
  action_taken text not null,  -- 'CORRECTED' | 'REJECTED' | 'CAPPED'
  logged_at    timestamptz not null default now()
);

create index idx_filter_log_date on public.ai_suggestion_filter_log (run_date desc);

-- ---------------------------------------------------------------------------
-- RLS — authenticated users read published suggestions; service_role writes
-- ---------------------------------------------------------------------------
alter table public.ai_suggestions          enable row level security;
alter table public.ai_suggestion_runs      enable row level security;
alter table public.ai_suggestion_filter_log enable row level security;

-- Published suggestions: any authenticated user can read
create policy "ai_suggestions_read_authed"
  on public.ai_suggestions
  for select
  using (auth.uid() is not null and is_published = true);

-- Run log and filter log: service_role only (admin review)
create policy "ai_suggestion_runs_service_only"
  on public.ai_suggestion_runs
  for all
  using (auth.role() = 'service_role');

create policy "ai_suggestion_filter_log_service_only"
  on public.ai_suggestion_filter_log
  for all
  using (auth.role() = 'service_role');

-- ---------------------------------------------------------------------------
-- HELPER FUNCTION — fetch today's valid published suggestions (Home screen)
-- Called by: GET /api/ai/suggestions
-- Returns: up to 20 rows ordered by confidence DESC
-- ---------------------------------------------------------------------------
create or replace function public.get_ai_suggestions_today()
returns table (
  symbol_code    text,
  signal_type    public.ai_signal_type,
  confidence_pct int,
  analysis_text  text,
  price_current  numeric,
  price_target   numeric,
  target_pct     numeric,
  generated_at   timestamptz,
  valid_until    timestamptz
)
language sql
stable
security definer
as $$
  select
    s.symbol_code,
    s.signal_type,
    s.confidence_pct,
    s.analysis_text,
    s.price_current,
    s.price_target,
    s.target_pct,
    s.generated_at,
    s.valid_until
  from public.ai_suggestions s
  where
    s.is_published = true
    and s.valid_until > now()
  order by s.confidence_pct desc, s.generated_at desc
  limit 20;
$$;
